make_tour("mth6412b-starter-code/projet/phase 5/shredder-julia/tsp/instances/abstract-light-painting.tsp", "mth6412b-starter-code/projet/phase 5/tours/light.tour")
make_tour("mth6412b-starter-code/projet/phase 5/shredder-julia/tsp/instances/lower-kananaskis-lake.tsp", "mth6412b-starter-code/projet/phase 5/tours/lake.tour")
make_tour("mth6412b-starter-code/projet/phase 5/shredder-julia/tsp/instances/nikos-cat.tsp", "mth6412b-starter-code/projet/phase 5/tours/cat.tour")
make_tour("mth6412b-starter-code/projet/phase 5/shredder-julia/tsp/instances/pizza-food-wallpaper.tsp", "mth6412b-starter-code/projet/phase 5/tours/pizza.tour")
make_tour("mth6412b-starter-code/projet/phase 5/shredder-julia/tsp/instances/the-enchanted-garden.tsp", "mth6412b-starter-code/projet/phase 5/tours/garden.tour")
make_tour("mth6412b-starter-code/projet/phase 5/shredder-julia/tsp/instances/tokyo-skytree-aerial.tsp", "mth6412b-starter-code/projet/phase 5/tours/tokyo.tour")

reconstruct_image("mth6412b-starter-code/projet/phase 5/tours/light.tour", "mth6412b-starter-code/projet/phase 5/shredder-julia/images/shuffled/abstract-light-painting.png", "mth6412b-starter-code/projet/phase 5/images reconstruites/light.png")
reconstruct_image("mth6412b-starter-code/projet/phase 5/tours/lake.tour", "mth6412b-starter-code/projet/phase 5/shredder-julia/images/shuffled/lower-kananaskis-lake.png", "mth6412b-starter-code/projet/phase 5/images reconstruites/lake.png")
reconstruct_image("mth6412b-starter-code/projet/phase 5/tours/cat.tour", "mth6412b-starter-code/projet/phase 5/shredder-julia/images/shuffled/nikos-cat.png", "mth6412b-starter-code/projet/phase 5/images reconstruites/cat.png")
reconstruct_image("mth6412b-starter-code/projet/phase 5/tours/pizza.tour", "mth6412b-starter-code/projet/phase 5/shredder-julia/images/shuffled/pizza-food-wallpaper.png", "mth6412b-starter-code/projet/phase 5/images reconstruites/pizza.png")
reconstruct_image("mth6412b-starter-code/projet/phase 5/tours/garden.tour", "mth6412b-starter-code/projet/phase 5/shredder-julia/images/shuffled/the-enchanted-garden.png", "mth6412b-starter-code/projet/phase 5/images reconstruites/garden.png")
reconstruct_image("mth6412b-starter-code/projet/phase 5/tours/tokyo.tour", "mth6412b-starter-code/projet/phase 5/shredder-julia/images/shuffled/tokyo-skytree-aerial.png", "mth6412b-starter-code/projet/phase 5/images reconstruites/tokyo.png")
